adminn/urls.py
from django.urls import path
from . import views

app_name = 'adminn'  # Namespace for admin URLs


urlpatterns = [
    #path('products/', views.product_list, name='product_list'),
    #path('addproducts',views.add_product, name='add_product'),
    path('adminhome/',views.adminhome, name='adminhome'),
    path('users/', views.users, name='users'),
    path('addproduct/', views.addproduct, name='addproduct'),
    path('productlist/', views.productlist, name='productlist'),
    path('deleteproduct/<int:product_id>/', views.deleteproduct, name = 'deleteproduct'),
    path('editproduct/<int:product_id>/', views.editproduct, name = 'editproduct'),
    path('product/image/<int:image_id>/delete/', views.delete_product_image, name='delete_product_image'),
    path('categorylist/', views.categorylist, name='categorylist'),
    path('addcategory/', views.addcategory, name='addcategory'),
    path('editcategory/<int:category_id>/', views.editcategory, name='editcategory'),
    path('deletecategory/<int:category_id>/', views.deletecategory, name='deletecategory'),
    path('block_user/<int:user_id>/', views.block_user, name='block_user'),
    path('unblock_user/<int:user_id>/', views.unblock_user, name='unblock_user'),
    path('orderlist/', views.orderlist, name='orderlist'),
    path('cancelorder/<int:order_id>/', views.cancelorder, name='cancelorder'),
    path('order_detaill/<int:order_id>/', views.order_detaill, name='order_detaill'),
    path('coupon/', views.coupon, name='coupon'),
    path('add_coupon/', views.add_coupon, name='add_coupon'),
    path('edit/coupon/<int:coupon_id>/',views.edit_coupon,name='edit_coupon'),
    path('delete/coupon/<int:coupon_id>/',views.delete_coupon,name='delete_coupon'),
   

    path('sales_report/', views.sales_report, name='sales_report'),
    path('sales/daily/', views.sales_report, {'period': 'daily'}, name='daily_sales_report'),
    path('sales/weekly/', views.sales_report, {'period': 'weekly'}, name='weekly_sales_report'),
    path('sales/monthly/', views.sales_report, {'period': 'monthly'}, name='monthly_sales_report'),
    path('sales/yearly/', views.sales_report, {'period': 'yearly'}, name='yearly_sales_report'),
    path('sales/custom/', views.sales_report, {'period': 'custom'}, name='custom_sales_report'),
   
    path('sales_report/pdf/', views.download_sales_reportpdf, name='download_sales_reportpdf'),
    path('sales_report/excel/', views.download_sales_reportexcel, name='download_sales_reportexcel'),

    path('custom_admin_homepage/', views.custom_admin_homepage, name='custom_admin_homepage'),

    
    path('add_variation/', views.add_variation, name='add_variation'),
    path('variationlist/', views.variationlist, name='variationlist'),

    path('process_order/<int:order_id>/', views.process_order, name='process_order'),
    path('ship_order/<int:order_id>/', views.ship_order, name='ship_order'),
    path('deliver_order/<int:order_id>/', views.deliver_order, name='deliver_order'),

]

carts/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('',views.cart,name='cart'),
    path('add_cart/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('apply_coupon/', views.apply_coupon, name='apply_coupon'),
    path('checkout/', views.checkout, name='checkout'),
    
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerceapp.urls')),
    path('store/', include('store.urls')),
    path('adminn/', include('adminn.urls', namespace='adminn')), #for custom user model in admin panel
    path('carts/',include('carts.urls')),
    path('orders/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

adminn/forms.py
# forms.py

from django import forms
from store.models import Product, ProductImage , Variation, VariationManager
from django.forms import modelformset_factory
from category.models import category
from orders.models import Coupon
from django.core.validators import MinValueValidator, MaxValueValidator
import os
from django.core.exceptions import ValidationError

class ProductForm(forms.ModelForm):
    discount = forms.DecimalField(
        label='Discount',
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Product
        fields = ['product_name', 'slug', 'description', 'price','discount', 'stock', 'is_available', 'category']
        widgets = {
            'product_name': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'stock': forms.NumberInput(attrs={'class': 'form-control'}),
            'is_available': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
        }

class ProductImageForm(forms.ModelForm):
    images = forms.FileField(
        widget=forms.TextInput(
            attrs={
                "name": "images",
                "type": "File",
                "class": "form-control",
                "multiple": "True",
            }
        ),
        label="",
        required=False,
    )

    class Meta:
        model = ProductImage
        fields = ['images']
    
class CategoryForm(forms.ModelForm):
    category_discount = forms.DecimalField(
        label='Category_Discount',
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )


    class Meta:
        model = category
        fields = ['category_name', 'slug','category_discount', 'description', 'cat_image']


class CouponForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})
    class Meta:
        model = Coupon
        fields = ['code', 'discount', 'valid_from', 'valid_to']
        widgets = {
            'valid_from': forms.DateTimeInput(attrs={'type': 'datetime-local' , 'class': 'form-control'}),
            'valid_to': forms.DateTimeInput(attrs={'type': 'datetime-local' , 'class': 'form-control'}),
        }


variation_category_choice = (
    ('color', 'Color'),
    ('size', 'Size'),
)


class VariationForm(forms.ModelForm):
    product = forms.ModelChoiceField(
        queryset=Product.objects.all(),
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    variation_category = forms.ChoiceField(
        choices=variation_category_choice,
        widget=forms.Select(attrs={'class': 'form-select'})
    )
    variation_value = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    is_active = forms.BooleanField(
        initial=True,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'})
    )


    class Meta:
        model = Variation
        fields = ['product', 'variation_category', 'variation_value', 'is_active']
        widgets = {
            'created_at': forms.DateTimeInput(attrs={'type': 'hidden'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['variation_value'].widget.attrs.update({'class': 'form-control'})

adminn/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.contrib import messages
from ecommerceapp.models import Account
from django.forms import modelformset_factory
from django.shortcuts import get_object_or_404
from .forms import ProductForm, ProductImageForm , CouponForm , VariationForm
from store.models import Product, ProductImage , Variation
from .forms import CategoryForm
from category.models import category
from orders.models import Order, OrderProduct , Coupon , Payment
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseServerError,HttpResponseNotFound
from django.utils import timezone
from django.db.models import Sum, Count , Q
from datetime import timedelta
from django.template.loader import render_to_string
from xhtml2pdf import pisa
import csv
import pandas as pd
from django.db.models import ExpressionWrapper
from django.db.models.functions import Coalesce
from django.db.models import Sum, F, ExpressionWrapper, DecimalField





# Create your views here.


def superuser_required(view_func):
    """
    Decorator for views that checks if the user is a superuser,
    redirects to the dashboard if not.
    """
    def _wrapped_view(request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_superadmin:
            return view_func(request, *args, **kwargs)
        else:
            return redirect('loginn')  # Redirect to the dashboard or any other page
    return _wrapped_view

def index(request):
    return render(request, 'index.html')

 
@superuser_required
def adminhome(request):
    products = Product.objects.all()  # Fetch all products or adjust the query as needed
    return render(request, 'adminn/adminhome.html', {'products': products})


@superuser_required
def users(request):
    # Fetch account objects from the database
    accounts = Account.objects.all()  # You can filter or order the queryset as needed
    
    # Pass the accounts queryset to the template context
    context = {
        'accounts': accounts

        }
    
    # Render the template with the context
    return render(request, 'adminn/users.html', context)

@superuser_required
def block_user(request, user_id):
    account = Account.objects.get(id=user_id)
    account.is_active = False  # Block the user
    account.save()
    messages.success(request, f"{account.username} has been blocked.")
    return redirect('adminn:users')  # Redirect back to the custom admin page

@superuser_required
def unblock_user(request, user_id):
    account= Account.objects.get(pk=user_id)
    if not account.is_active:
        account.is_active = True  # Unblock the user
        account.save()
        messages.success(request, f"{account.username} has been unblocked.")
    else:
        messages.error(request, f"{account.username} is already unblocked.")
    return redirect('adminn:users')  # Redirect back to the custom admin page

@superuser_required
def addproduct(request):
    productform = ProductForm()
    imageform = ProductImageForm()
    
    if request.method == 'POST':
        
        files = request.FILES.getlist('images')
        
        productform = ProductForm(request.POST, request.FILES)
        if productform.is_valid():
            product = productform.save(commit=False)
           
            product.save()
            print(request, "Product created successfully")
            
            for file in files:
                ProductImage.objects.create(product=product, image=file)
            
            return redirect("adminn:productlist")
    # Retrieve products ordered by creation date in descending order
    products = Product.objects.all().order_by('-created_date')

    context = {"form": productform, "form_image": imageform, "products": products}
    return render(request, "adminn/addproduct.html", context)

@superuser_required
def productlist(request):
    products = Product.objects.all().order_by('-created_date') 
    return render(request, 'adminn/productlist.html', {'products': products})

@superuser_required
def deleteproduct(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    product.is_active = False
    product.save()
    return redirect('adminn:productlist')

@superuser_required
def editproduct(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    form = ProductForm(instance=product)
    image_form = ProductImageForm()

    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        image_form = ProductImageForm(request.POST, request.FILES)
        if form.is_valid() and image_form.is_valid():
            form.save()
            if request.FILES.getlist('images'):
                for image in request.FILES.getlist('images'):
                    ProductImage.objects.create(product=product, image=image)
            messages.success(request, "Product edited successfully")
            return redirect("adminn:productlist")
        else:
            messages.error(request, "Error editing product. Please check the form.")
    else:
        # This ensures existing images can be seen and edited
        image_form = ProductImageForm()
    # Fetch existing images and pass them to the template
    existing_images = product.image.all()
    return render(request, "adminn/editproduct.html", {"form": form, "image_form": image_form, "existing_images": existing_images })

@superuser_required
def delete_product_image(request, image_id):
    image = get_object_or_404(ProductImage, id=image_id)
    image.delete()
    messages.success(request, "Image deleted successfully")
    return redirect('adminn:editproduct', product_id=image.product.id)


@superuser_required
def categorylist(request):
    categories = category.objects.all()
    return render(request, 'adminn/categorylist.html', {'categories': categories})

@superuser_required
def addcategory(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('adminn:categorylist')
    else:
        form = CategoryForm()
    return render(request, 'adminn/addcategory.html', {'form': form})

@superuser_required
def editcategory(request, category_id):
    category_obj = get_object_or_404(category, id=category_id)  # Use the model name here
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=category_obj)
        if form.is_valid():
            form.save()
            return redirect('adminn:categorylist')
    else:
        form = CategoryForm(instance=category_obj)

    return render(request, 'adminn/editcategory.html', {'form': form})

@superuser_required
def deletecategory(request, category_id):
    category = get_object_or_404(category, id=category_id)
    # Soft delete all products associated with the category
    products_to_delete = Product.objects.filter(category=category)
    products_to_delete.update(is_active=False)
    
    # Deactivate the category
    category.is_active = False
    category.save()# Update the 'is_active' field to False instead of deleting
    return redirect('adminn:categorylist')

@superuser_required
def orderlist(request):
    orders = Order.objects.all().order_by('id')
    return render(request, 'adminn/orderlist.html', {'orders': orders})

@superuser_required
def cancelorder(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.is_ordered = False
    order.status = 'Cancelled'
    order.save()
    return redirect('adminn:orderlist')

@superuser_required
def order_detaill(request, order_id):
    order_detail = OrderProduct.objects.filter(order__order_number = order_id)
    order = Order.objects.get(order_number = order_id)
    subtotal = 0
    for i in order_detail:
        product = Product.objects.get(id=i.product_id)  # Retrieve the product
        subtotal += product.price_after_discount() * i.quantity  # Calculate subtotal using price_after_discount

    # Fetching payment method from the related Payment object
    payment_method = order.payment.payment_method if order.payment else None
    
    # Retrieve coupon discount
    coupon_discount = 0
    if order.coupon:
        try:
            coupon = Coupon.objects.get(code=order.coupon)
                # Check if the coupon is valid
            if coupon.valid_from <= order.created_at <= coupon.valid_to:
                coupon_discount = coupon.discount
        except Coupon.DoesNotExist:
            pass

    context = {
        'order_detail' : order_detail,
        'order' : order,
        'subtotal' : subtotal,
        'payment': order.payment,
        'payment_method': payment_method,
        'coupon_discount': coupon_discount,
        
    }

    return render(request, 'adminn/order_detaill.html', context)


@superuser_required
def coupon(request):
    coupons = Coupon.objects.all()
    return render(request, 'adminn/coupon.html', {'coupons': coupons})

@superuser_required
def add_coupon(request):
    if request.method == 'POST':
        form = CouponForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('adminn:coupon')  # Redirect to the coupon list page after successful addition
    else:
        form = CouponForm()
    return render(request, 'adminn/add_coupon.html', {'form': form})

@superuser_required
def edit_coupon(request, coupon_id):
    coupon = get_object_or_404(Coupon, id=coupon_id)
    if request.method == "POST":
        form = CouponForm(request.POST, instance=coupon)
        if form.is_valid():
            form.save()
            messages.success(request, "Coupon updated successfully!")
            return redirect("adminn:coupon")
        else:
            messages.error(request, form.errors)
    else:
        form = CouponForm(instance=coupon)
    return render(

templates/adminn/adminbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin</title>
    <!-- Add Bootstrap CSS link -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <style>
        /* Add custom styles here */
        body {
            background-color: #f8f9fa; /* Light gray background */
            font-family: Arial, sans-serif; /* Specify font family */
            padding-top: 50px; /* Add space at the top */
        }

        .container {
            max-width: 800px; /* Limit content width */
            margin: auto; /* Center content horizontally */
            text-align: center; /* Center text */
        }

        h1 {
            color: #007bff; /* Blue heading */
            margin-bottom: 30px; /* Add space below heading */
        }

        .navbar-brand {
            font-weight: bold; /* Make navbar brand text bold */
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'adminn:adminhome' %}">Admin Panel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'adminn:users' %}">Users</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'adminn:categorylist' %}">Categories</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'adminn:productlist' %}">Products</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'adminn:variationlist'  %}">Variations</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'adminn:orderlist' %}">Orders</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'adminn:coupon' %}">Coupons</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'adminn:sales_report' %}">Sales Report</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'adminn:custom_admin_homepage' %}">Sales Chart</a>
            </li>
             

          </ul>
          <form class="form-inline my-2 my-lg-0">
            <button class="btn btn-outline-danger my-2 my-sm-0" type="submit"><a class="nav-link" href="{% url 'logout' %}">Sign Out</button></a>
          </form>
        </div>
      </nav>
      
   <!-- Add Bootstrap JS and Popper.js scripts (order matters) -->
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
   <!-- Js Plugins -->
   <script src="{%static 'js/jquery-3.3.1.min.js' %}"></script>
   <script src="{%static 'js/bootstrap.min.js' %}"></script>
   <script src="{%static 'js/jquery.magnific-popup.min.js' %}"></script>
   <script src="{%static 'js/jquery-ui.min.js' %}" ></script>
   <script src="{%static 'js/mixitup.min.js' %}"></script>
   <script src="{%static 'js/jquery.countdown.min.js' %}"></script>
   <script src="{%static 'js/jquery.slicknav.js' %}"></script>
   <script src="{%static 'js/owl.carousel.min.js' %}"></script>
   <script src="{%static 'js/jquery.nicescroll.min.js' %}"></script>
   <script src="{%static 'js/main.js' %}"></script>
   <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



</body>
</html>

{% block content %}

{% endblock %}

templates/adminn/categorylist.html
{% extends 'adminn/adminbase.html' %}
{% block content %}
{% include 'includes/alerts.html' %}

<h2 class="text-center pt-5 pb-3">CATEGORY LIST</h2>
<div class="container">
    <div class="d-flex justify-content-end mb-3"> <!-- Flexbox container for button alignment -->
        <a href="{% url 'adminn:addcategory' %}" class="btn btn-primary">ADD CATEGORY</a>
    </div>
    <table class="table table-bordered table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Image</th>
                <th>Actions</th> <!-- New column for actions -->
               
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
                {% if category.is_active %}
            <tr>
                <td>{{ category.category_name }}</td>
                <td>{{ category.cat_image }}</td> <!-- Display image if available -->
                
                <td>
                    <a href="{% url 'adminn:editcategory' category.id %}" class="btn btn-sm btn-primary">Edit</a>
                    <a href="{% url 'adminn:deletecategory' category.id %}" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this category?');">Unlist</a>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock content %}

templates/adminn/coupon.html
{% extends 'adminn/adminbase.html' %}
{% block content %}
{% include 'includes/alerts.html' %}
<h2 class="text-center pt-5 pb-3">COUPON LIST</h2>
<div class="container">

<div class="text-right mb-3">
    <a href="{% url 'adminn:add_coupon' %}" class="btn btn-primary mb-3">ADD COUPON</a>
    </div>
    </div>
    <div class="container">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Code</th>
                <th>Discount</th>
                <th>Valid From</th>
                <th>Valid To</th>
                <th>Actions</th>
                
            </tr>
        </thead>
        <tbody>
            {% for coupon in coupons %}
            <tr>
                <td>{{ coupon.code }}</td>
                <td>{{ coupon.discount }}</td>
                <td>{{ coupon.valid_from }}</td>
                <td>{{ coupon.valid_to }}</td>
                <td><a href="{% url 'adminn:edit_coupon' coupon.id %}" class="btn btn-sm btn-primary">Edit</a>
                <td><a href="{% url 'adminn:delete_coupon' coupon.id %}" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this coupon?');">Delete</a>        
            </tr>
            {% endfor %}
        </tbody>

       
    </table>
</div>
{% endblock %}

templates/adminn/editproduct.html
{% extends 'adminn/adminbase.html' %}
{% block content %}
{% include 'includes/alerts.html' %}
<div class="container pb-3">
    <div class="card">
        <div class="card-body">
            <h2 class="text-center pt-5 pb-5">EDIT PRODUCT</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="form-group">
                    <label>Existing Images:</label>
                    <div>
                        {% for image in existing_images %}
                            <img src="{{ image.image.url }}" alt="{{ product.product_name }}" class="img-thumbnail" style="width: 100px; height: 150px; margin: 5px;">
                            <a href="{% url 'adminn:delete_product_image' image.id %}">Delete</a>
                        {% endfor %}
                    </div>
                </div>
                {{ image_form.as_p }}
                <input type="submit" class="btn btn-primary" value="Save Changes">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/adminn/orderlist.html
{% extends 'adminn/adminbase.html' %}
{% block content %}
{% include 'includes/alerts.html' %}
<h2 class="text-center pb-5 pt-5">ORDERS LIST</h2>

        <table class="table table-bordered">
        <thead>
            <tr>
                <th>Order No</th>
                <th>Full Name</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Order Total</th>
                <th>Coupons</th>
                <th>Tax</th>
                <th>Order Date</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr>
                <th scope="row"><a href="{% url 'adminn:order_detaill' order.order_number %}">{{order.order_number}}</a></th>
                <td>{{ order.full_name }}</td>
                <td>{{ order.phone_number }}</td>
                <td>{{ order.email }}</td>
                <td>{{ order.order_total}}</td>
                <td>{{order.coupon}}</td>
                <td>{{ order.tax }}</td>
                <td>{{ order.created_at }}</td>
                <td>{{order.status}}</td>

                    <td>
                        <div class="pl-3">
                            <form action="{% url 'adminn:process_order' order.id %}" method="post">
                              {% csrf_token %}
                              <div class="pb-2 ">
                              <button type="submit" class="btn btn-primary w-75">Process</button>
                            </div>
                            </form>
                            <form action="{% url 'adminn:ship_order' order.id %}" method="post">
                                {% csrf_token %}
                                <div class="pb-2 ">
                                <button type="submit" class="btn btn-success w-75">Ship</button>
                            </div>
                              </form>
                              <form action="{% url 'adminn:deliver_order' order.id %}" method="post">
                                {% csrf_token %}
                                <div class="pb-2">
                                <button type="submit" class="btn btn-warning w-75">Deliver</button>
                            </div>
                              </form>
                              <form action="{% url 'cancel_order' order_number=order.order_number %}" method="post">
                                {% csrf_token %}
                                <div class="pb-2">
                                <button type="submit" class="btn btn-danger w-75">Cancel</button>
                            </div>
                              </form>

                        </div>  
                </td>

                
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}

templates/adminn/productlist.html
{% extends 'adminn/adminbase.html' %}
{% block content %}
{% include 'includes/alerts.html' %}
<h2 class="text-center pt-5 pb-4 ">PRODUCT LIST</h2>
<div class="text-right mb-3">
    <a href="{% url 'adminn:addproduct' %}" class="btn btn-primary mb-3">ADD PRODUCT</a>
    </div>
        <table class="table table-bordered table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Discount</th>
                <th>Stock</th>
                <th>Images</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            {% if product.is_active %}
            <tr>
                <td>{{ product.product_name }}</td>
                <td>{{ product.description }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.discount }}</td>
                <td>{{ product.stock }}</td>
                <td>
                    {% for image in product.image.all %}
                    <img src="{{ image.image.url }}" alt="{{ product.product_name }}" class="img-thumbnail" style="width: 100px;height: 150px;">
                    {% endfor %}
                </td>
                <td>
                <div class="btn-group" role="group">
                    <a href="{% url 'adminn:editproduct' product.id %}" class="btn btn-sm btn-primary">Edit</a>
                    <a href="{% url 'adminn:deleteproduct' product.id %}" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this category?');">Unlist</a>
                    </div>
                </td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
    
{% endblock content %}